---
title: 'Bad Student, Good Patient: When Classroom Behavior Becomes Medicated'
author: "Ruby Ashman"
date: "2024-10-25"
output:
  pdf_document: default
  word_document: default
fontsize: 12pt
---

Upon their long lists of Generation Z related grievances or praise, many older generations have seemed to identify the sharp increase in mental illness diagnoses, often relaying some expression of “No one had that when I was a kid”. While it is fair to say that claim is likely untrue, rising rates of anxiety, depression, attention deficit disorder, and post traumatic stress disorder have distinguished the current adolescent to young adult age group. According to a longitudinal study published in the Journal of Abnormal Psychology, major depressive episodes among adolescents increased 52% from 2005 to 2017, mirrored closely by young adults, who reported a 63% increase from 2009 to 2017. Researchers across the world have proposed countless instigators of this noticeable increase, such as higher screen time hours, growing awareness of sociological and environmental issues, decreasing stigma around mental health struggles, and sterner school structures. Attention-deficit hyperactivity disorder, or ADHD, has followed a similar trend with a diagnosis increase of nearly 4.1% from 1997 to 2016. Despite the universal upward trend in many mood and behavioral disorders, rising ADHD rates specifically have seemed to take the public by storm, fueling the creation of the “ADHD Epidemic” term, which is now widely used in conversations surrounding the disorder. In trying to explain this pattern, a select group of researchers have honed in on the diagnostic criteria that qualify this disorder, and have proposed the question of possible overdiagnosis or misdiagnosis serving as a factor in the surge of ADHD diagnoses.  

Six symptoms of inattention and six symptoms of hyperactivity, onset before age seven, impairment in two or more settings, clinically significant impairment, and symptoms that are not better accounted for by another disorder make up both the ICD-10 research criteria as well as the DSM-IV combined type diagnosis standards for ADHD. Attention-Deficit/Hyperactivity Disorder provides an explanation for many as to why certain children can’t stay seated in class and are found speaking out of turn constantly. Unfortunately, these behaviors have become deeply linked to ADHD despite not being conclusive of the disorder and many other manifestations of ADHD, such as inattention and disorganization, have been forgotten. This heuristic reasoning, or crafting one’s perception based on familiarity and limited knowledge, poses a significant threat to the therapeutic community as diagnoses must be made with strict benchmarks, not based on personal perception. One massive consequence of this effect is the overdiagnosis of ADHD and following treatment of individuals who did not display every symptom necessary to be diagnosed, likely only demonstrating the symptoms that made up their therapist's vision of the disorder. It is essential to recognize that each symptom of this disorder is equally important and therefore should not be prioritized as a reason for diagnosis if the patient falls short of another symptom.

Another unfortunate consequence of heuristic reasoning in the case of ADHD diagnosis is that the symptoms most quickly and easily affiliated with the disorder are the most common manifestations in young boys uniquely. Boys are found to be more impulsive and disruptive in a classroom setting, while girls are more often inattentive and lacking the organization necessary for productivity. Due to these distinctive expressions, it is understandable why not only boys would be recommended for consultation first, but more quickly diagnosed, given their expression closely aligns with the stereotype of an ADHD child. This explanation, however, assumes ADHD itself is no more likely in boys than girls and the disorder is expressed differently but equally across both genders. If this were true, the prevalence of ADHD in girls and boys would be equivalent, despite the observed contrasts in symptoms by gender. Essentially, children that expressed ADHD in ways disruptive in a classroom or refined behavioral setting would be diagnosed at the same rates as children who expressed ADHD in less disruptive ways, such as zoning out or maintaining a disorganized personal environment. Unfortunately, a child causing outward disruptions is much more likely to have their behavior investigated, and combined with the evidence of ADHD in boys being much more likely to manifest this way, a gender correlated diagnosis pattern has been suspected. While this claim is still being actively investigated and researched, it is accepted that the extent to which more boys than girls are being diagnosed is not representative of community samples that take into account these expression variances. Population based studies often quantify males to be three times more likely to have ADHD, however clinical studies tend to yield males to be six to nine times more likely to have ADHD, quite a significant inconsistency (Bruchmüller et al., 2012).  In other words, even if boys are more susceptible than girls to ADHD, the disparity in diagnosis must also be attributed to alternative factors, as the asymmetry between population based study gender ratios and clinical sample diagnosis gender ratios is greater than solely disproportionate occurrence.

Katrin Bruchmüller, Jürgen Margraf, and Silvia Schneider hypothesize both the overdiagnosis and seemingly gender biased diagnosis of ADHD are the effects of therapists straying from the guidelines stated in both the Diagnostic and Statistical Manual of Mental Disorders and the International Classification of Diseases criteria. To further explore this suspicion, this group of psychologists randomly selected 1000 individuals working as therapists, specializing in adolescents, in one of the four following German states: Baden-Württemberg, Bavaria, Lower Saxony, and Hesse. In this study, working as a therapist was an umbrella term for child psychiatrists, psychologists, and social workers. The numeric reasoning that prompted the sample size choice of 1000 lied in the construction of a power analysis to determine an appropriate sample size that accurately represented the population of therapists in these regions, given a predicted response rate of 40%. Once the sample was selected, the psychologists carefully constructed eight groups of 125, attempting to form a roughly equal gender and occupation distribution between groups, ideally minimizing the relative effect of these factors on their results. The psychologists sent each therapist a cover letter, case vignette, and questionnaire.

Each member of the initial sample received one of eight distinct vignettes, depending on their group assignment. In identical cover letters, the participants were asked to approach the vignette they were sent as a real patient reaching out to them, and to diagnose the patient as they would in an in person meeting. The eight vignettes were meticulously designed to reflect the qualifications of ADHD diagnosis to varying extents in order to evaluate the frequency of diagnosis without all symptoms present. It is important to note that all symptoms outlined in the DSM-IV combined type and ICD-10 research criteria must be met for legitimate diagnosis. Importantly, the DSM-IV combined type ADHD criteria and the ICD-10 research criteria are identical, so ideally therapists familiar with either of the guidelines should determine the same diagnosis. 

The eight vignettes were further grouped based on outlined symptoms, with the two symptomatically identical vignettes in each group differing only by one factor–their gender. The first vignette depicted a youth who met all five criteria required for clear ADHD diagnosis, according to the guidelines referenced, this vignette was the only scenario where ADHD was the unquestionable diagnosis. In the second vignette, the theoretical patient was a youth who was missing two of the necessary criteria for ADHD diagnosis, lacking two settings of disruption and onset prior to age seven. The third vignette lacked the same two criteria as the second vignette, and additionally lacked the six symptoms of inattentiveness and hyperactivity necessary for diagnosis. According to the diagnostic resources the therapists were asked to utilize, no ADHD diagnosis should have been given as a response to vignette two or three, given not all necessary symptoms were presented by the vignettes. Vignette four portrayed a youth with symptoms of GAD, generalized anxiety disorder, which has symptom overlap with ADHD. Despite similarities, vignette four did not fulfill all ADHD criteria and did fulfill all GAD criteria. The response rate did not differ significantly between vignettes. 

Randomization was ensured by comparing the distribution of age, theoretical orientation (therapeutic approach), professional experience, gender, and DSM-IV/ICD-10 education between all vignette groups. No significant differences between groups were found in any of these categories. Prior to sample outreach, the drafted vignettes were examined by 14 diagnosticians, who gave a diagnosis, explained their confidence in the given diagnosis, and articulated which aspects of the vignette they found the most puzzling. The diagnosticians selected all held degrees in psychology, completed a standardized training course on structured interviewing, and had passed a reliability check. These qualifications were the reasoning behind the selection of these specific individuals, and further accredited their responses. A meeting was then conducted with five researchers and diagnosticians to further alter the vignettes in order to increase their reliability. This group of five were considered experts, each holding a master’s or doctoral degree in the field of clinical psychology. After adjustment, the vignettes were retested by consulting four new diagnosticians, who all met the outlined requirements, and the accuracy of diagnosis increased to 100% for each vignette. The researchers then disclosed the purpose of the study to the final diagnosticians they consulted, who recommended slight changes to minimize ambiguity, which were incorporated to produce the final vignettes sent to the sample. 

Following the therapist’s exposure to their assigned vignette, they were asked in a questionnaire to diagnose both by recording the name and the F code of the disorder. Answers were separated into two categories, ADHD diagnosis and no ADHD diagnosis. F codes 90.0 or 90.1 or identification of ADHD specifically led to response classification in the ADHD diagnosis category. The no ADHD diagnosis category responses were further grouped into four categories based on the responses of the sample: not enough information for diagnosis, no diagnosis, other diagnosis, and suspected ADHD. Three raters were responsible for the categorization of responses, with Cohen's agreement between .944 and .958. The questionnaire also requested the therapists share whether or not they recommended treatment. If they responded yes (that they do recommend treatment), they were asked to further answer if they did or did not recommend medication and if they did or did not recommend psychotherapeutics. Demographic data referenced throughout the study was also collected in the questionnaire. 

Between September 2009 and November 2009, the psychologists received 473 responses (a response rate of approximately 47%), 463 of which were interpreted for data due to their inclusion of all essential information. Participation was incentivized by exchanging the results of the study for their contribution, and a single reminder letter was sent out after six weeks of no response. In order to evaluate the closeness of the responsive sample with the total population of German adolescent therapists, the gender and age distribution of both groups were produced, from which a mean age and percentage of women were calculated. The sample mean age was 53.25 years, while the true population mean age was 53.54 years, additionally the sample contained 68.4% women, and the true population contained 69.3% women (Bruchmüller et al., 2012). The similarity in these values affirms the sample to be nearly representative of the population of adolescent therapists in Germany. Additionally, a distribution of the occupations (child psychiatrist, psychologist, or social worker) held by sample participants was constructed in order to further characterize the representativeness of the chosen sample. The participating sample was calculated to contain 17.8% psychiatrists, 54.5% psychologists, and 27.7% social workers. No significant difference was found in the distribution of professional occupations between the initial random sample of 1,000 and the participating sample of 473, with a calculated chi squared value of 0.473 and a p-value of 0.789. 

Before the researchers were able to reveal if there is evidence for the overdiagnosis of ADHD, they had to define overdiagnosis numerically. The definition posed by Sciutto and Eisenberg (2007) was favored, defining overdiagnosis as the significant overpowering of false negative diagnoses by false positive diagnoses. In this study, a false negative diagnosis would be characterized by a therapist not diagnosing ADHD for a vignette that fulfilled the ADHD qualifications and a false positive diagnosis would be characterized by a therapist diagnosing ADHD for a vignette that did not fulfill ADHD qualifications. To determine whether the proportion of false positives significantly exceeded the proportion of false negatives, a chi square test was conducted to determine if the difference in the two values was statistically significant.

After collection and categorization, the researchers calculated that in the six vignettes that did not fulfill ADHD symptom conventions, 16.7% (57 of 342) of the therapists diagnosed ADHD. Alternatively, in the two vignettes that did fulfill ADHD symptom conventions, 78.9% (90 of 114) diagnosed ADHD, and 7% (8 of 114) gave a diagnosis other than ADHD. The remaining therapists either responded that they did not have enough information, or that they suspected ADHD, which was not included in the false negative category. The rate of false positive diagnoses (16.7%) was then compared with the rate of false negative diagnoses (7%) using a chi-square test, which concluded there were significantly more false positive than false negative diagnoses, supported by a calculated p-value of .011. Subsequently, a second analysis was conducted, excluding the data of therapists which responded that they did not have enough information to give a diagnosis and the therapists that responded they suspected ADHD. This adjustment increased both the percentage of false positives and false negatives, 20% (57 of 285) and 8.2% (8 of 98) respectively, and after a chi-square test was conducted the proportion of false positives was determined to significantly exceed the proportion of false negatives, supported by a p-value of .008.

Additionally, with the goal of determining if the gender of the case vignette patient had an impact on the therapist’s diagnosis, a multiple logistic regression analysis was constructed. The dependent variable was identified to be the therapist’s diagnosis (either ADHD or no ADHD) and the predictor variable was the gender of the vignette (girl or boy). The therapist’s gender, age, approach/orientation, experience, and occupation were also evaluated as variables that could influence diagnostic decision. The interactions of gender of case vignette and gender of therapist, as well as gender of case vignette and type of vignette (ADHD symptom fulfillment or not) were also used as predictors. Tests for multicollinearity were also conducted prior to this analysis. In probing for multicollinearity, researchers probed the linear relationship of the independent predictor variables used. It was essential to conduct this test in order to understand the correlation between any two predictor variables, such as occupation and gender, and to further develop a prediction model based on the outlined characteristics. In the process of the multiple logistic regression analysis and multicollinearity tests the researchers maintained the goal of determining which variables correlated closely with ADHD diagnosis and overdiagnosis, in order to better understand this phenomenon.

Under the expectation that ADHD would be diagnosed more frequently in boys, a logistic regression analysis was conducted to determine if vignette gender, in addition to the predictors listed above, had a significant impact on the diagnosis of ADHD. The equation with the predictors was confirmed to fit the data significantly better than the equation that did not include the predictors, with a chi-square value of 120.688 and a p-value of less than .0001. The gender of the vignette was a significant predictor, as the odds of diagnosis of ADHD in a boy vignette was more than twice the odds of diagnosis of ADHD in a girl vignette, with an odds ratio of 2.66 and p-value of .034. For the ADHD fulfillment vignette (the first vignette) there was no significant difference in ADHD diagnoses between the boy (77%) and girl (88%) vignettes. On the other hand, in vignettes 2-4, the boy vignettes received approximately twice as many diagnoses as the girl vignettes. For the girl vignettes, there was no statistically significant difference in the proportion of false positives (11.3%) and false negatives (7.5%). However in the boy vignettes, there was a statistically significant difference in false positives (21.8%) and false negatives (6.6%), confirmed by a chi-square value of 7.12 and a p-value of .008.

After analyzing the impacts of various characteristics of the therapist’s on their diagnoses, only the gender of the therapist was determined to have a significant influence on their resulting diagnosis. The calculated odds ratio of 0.267, and p-value of .001, demonstrated male therapists were significantly more likely to diagnose ADHD than female therapists. The interaction of the gender of therapist and gender of child in case vignette was determined to be insignificant, with a p-value of .157. For female therapists, there was no significant difference in the proportion of false positive diagnoses (12.3%) and false negative diagnoses (9.6%), even when individualized by boy and girl vignettes. On the other hand, for male therapists, the proportion of false positive diagnoses (25.7%) significantly exceeded the proportion of false negative diagnoses (2.6%), with a chi-square value of 9.441, a p-value of .002, and an odds ratio of 12.82. When vignettes were individualized by gender for male therapists, the proportion of false positives to false negatives was only significant for boy vignettes (39.2% to 5.3%), which yielded a chi-square value of 8.075, a p-value of .004, and an odds ratio quantity of 12.2. 

Lastly, in order to understand the impact of overdiagnosis on treatment recommendation, chi-square tests were performed on treatment recommendations of the therapists who diagnosed ADHD against the treatment recommendations of the therapists who did not diagnose ADHD for the six vignettes that did not fulfill ADHD criteria. The therapists who misdiagnosed ADHD in these vignettes were significantly more likely to recommend both medication, with a p-value of .001, and psychotherapeutic treatment, with a p-value of .041, and significantly less likely to recommend no treatment, with a p-value of .014, than the therapists who did not diagnose ADHD for these vignettes. Therefore the therapists who were more likely to overdiagnose were also more likely to recommend treatment. 

Consistently, boy vignettes in the study were more likely to be diagnosed for ADHD than girl vignettes, and proof of overdiagnosis was found only for boy vignettes, implying that boys are also more likely to be overdiagnosed. In cases where all ADHD criteria were fulfilled both vignettes were likely to be diagnosed, but in cases where a few criteria were lacking, boys were significantly more likely to be diagnosed. Most other studies have claimed the disparity in diagnosis of ADHD between boys and girls to be related to the underidentification of ADHD in girls, due to differences in expression. The data analyzed here supports this disparity to be due to the overdiagnosis in boys, as opposed to the underdiagnosis in girls. Since the vignettes showed identical symptoms for both boys and girls, the effect of differences in manifestation is eliminated and therefore debunks this reason for diagnosis disparity between boys and girls. Another significant finding of the data was the increased likelihood of therapists who misdiagnosed ADHD to subsequently be more likely to recommend treatment. Many adverse health effects can result from ingestion of medication that is not needed, especially when consumed by children who may struggle to articulate its effects on them. Beginning to take stimulant medication at a young age can also increase dependence on the medication, particularly in children who will be undergoing formative years under the influence of the medication they are incorrectly prescribed. While health care systems and health insurance circumstances vary greatly by patient, it is generally understood that taking a medication not required by one’s health is dangerous and expensive, and no one deserves to be doing so without their knowledge.

The conversation surrounding overdiagnosis is extremely complex, and it is essential to avoid drawing quick assumptions such as students faking symptoms for access to study aiding medications, as these claims have had significant impacts on the incorrect stigma of those with ADHD lacking discipline. One common sentiment resisting the possibility of overdiagnosis lies in the ideology of better safe than sorry, which does not always stand true. An alternative application of this lies in benign tumors, and their subsequent treatment. Despite being non cancerous and unable to spread, many patients seek removal or other remediation techniques even after being guaranteed their safety from a doctor, sometimes putting themselves in higher risk situations. Similar situations are reflected within the population of those with ADHD, particularly in cases where medication is prescribed, despite not being the best route of treatment. In these scenarios, psychiatrists are faced with the moral dilemma of prescribing a medication that may or may not increase the quality of life of their patient. By providing medication therapies, a psychiatrist could alleviate the stress of their patient by providing a solution, and allow them to escape the time exhaustive sequence of expensive appointments. Some might even argue this benefits the patient, allowing them to move forward after diagnosis, and the healthcare system as a whole, making time for the next subset of patients seeking access to treatment. While short term benefits may be found in the decision to overdiagnose, the negative long term effects on those with ADHD must be taken into account. Most importantly, by receiving a treatment that is not the best fit for them as an individual, patients are being deceived into believing they are receiving the highest quality of care, which is not true. Additionally, the distress that results from the medication proving ineffective will only cause additional disturbance to the patient, and bring them back to square one of their mental health journey. 

To understand the dynamic ethical consequences of overdiagnosis, it is essential to first understand who benefits from overdiagnosis and how. Pharmaceutical and diagnostic manufacturers sit extremely high on this list, given their consumer base is reliant on a diagnosed population’s dependence on the medications they manufacture. Realistically, this relationship is a deeply rooted one, and it is important that diagnostic trends and medication production are closely monitored over time. In the United States specifically, the health insurance system has also created pressure to diagnose and medicate faster, given the high volume of patients who need care, and increasing expenses associated with health consultations in general. While an ideal system might require multiple visits with multiple different specialists prior to diagnosis and medication referral, this would require a complete restructuring of the way mental illness is treated, and put increased pressure on an already fragile health care system. The cost of inaction, however, would be paid by those most vulnerable to misdiagnosis. 

Lastly, drawn from the high proportion of false positive diagnoses, is the possibility criteria are not properly fitting the disorder itself, and further alterations of these guidelines might be necessary. While this observation might be worth further investigation, it is fair to say from the data accumulated in the study that therapists are not strictly abiding by the guidelines articulated in these criteria, and might not be aware of the large impact effects like the representativeness heuristic are having on their diagnoses. Understandably, therapists cannot be expected to be perfect, but in their promises to do no harm it is essential they understand the dangers of deviation from diagnosis guidelines. Reformulating the process by which therapists diagnose ADHD and similar disorders, as well as setting guidelines regarding their familiarity with these diagnostics could be extremely helpful in remediating the overdiagnosis of ADHD amongst adolescents. 

\newpage

References


Bruchmüller, K., Margraf, J., & Schneider, S. (2012). Is ADHD diagnosed in accord with diagnostic criteria? Overdiagnosis and influence of client gender on diagnosis. Journal of consulting and clinical psychology, 80(1), 128–138. https://doi.org/10.1037/a0026582 

Twenge, J. M., Cooper, A. B., Joiner, T. E., Duffy, M. E., & Binau, S. G. (2019). Age, period, and cohort trends in mood disorder indicators and suicide-related outcomes in a nationally representative dataset, 2005-2017. Journal of abnormal psychology, 128(3), 185–199. https://doi.org/10.1037/abn0000410

Xu G, Strathearn L, Liu B, Yang B, Bao W. Twenty-Year Trends in Diagnosed Attention-Deficit/Hyperactivity Disorder Among US Children and Adolescents, 1997-2016. JAMA Netw Open. 2018;1(4):e181471. doi:10.1001/jamanetworkopen.2018.1471  